# Gabriel Coelho Severino

### Listar todos os produtos
GET http://localhost:8000/produto HTTP/1.1

### Listar um produto específico
GET http://localhost:8000/produto/1 HTTP/1.1

### Cadastrar um produto
POST http://localhost:8000/produto HTTP/1.1
Content-Type: application/json

{
    "id_produto": 1,
    "nome": "Pastel de Carne",
    "descricao": "Delicioso pastel recheado com carne moída",
    "foto": "cGFzdGVs",
    "valor_unitario": 8.50
}

### Atualizar um produto
PUT http://localhost:8000/produto/1 HTTP/1.1
Content-Type: application/json

{
    "id_produto": 1,
    "nome": "Pastel de Queijo",
    "descricao": "Delicioso pastel recheado com muito queijo",
    "foto": "cGFzdGVs",
    "valor_unitario": 8.00
}

### Deletar um produto
DELETE http://localhost:8000/produto/1 HTTP/1.1
