# Gabriel Coelho Severino

### Listar todos os funcionários
GET http://localhost:8000/funcionario/ HTTP/1.1

### Listar um funcionário específico
GET http://localhost:8000/funcinario/1 HTTP/1.1

### Cadastrar um funcionário
POST http://localhost:8000/funcionario HTTP/1.1
Content-Type: application/json

{
    "nome": "João",
    "matricula": "123456",
    "cpf": "111.222.333-44",
    "telefone": "11999999999",
    "grupo": 1,
    "senha": "senha_segura"
}

### Atualizar um funcionário
PUT http://localhost:8000/funcionario/1 HTTP/1.1
Content-Type: application/json

{
    "nome": "João Silva",
    "matricula": "123456",
    "cpf": "111.222.333-44",
    "telefone": "11999999999",
    "grupo": 2,
    "senha": "nova_senha_segura"
}

### Deletar um funcionário
DELETE http://localhost:8000/funcionario/1 HTTP/1.1